export const SET_FOOD_ACTIVE = "SET_FOOD_ACTIVE";
<<<<<<< HEAD
export const INIT_FOOD_LIST = "INIT_FOOD_LIST";
export const REQUEST_FOOD_LIST = "REQUEST_FOOD_LIST";
=======
export const INIT_FOOD_LIST = 'INIT_FOOD_LIST';
export const REQUEST_FOOD_LIST = "REQUEST_FOOD_LIST";
>>>>>>> f2b02544ed3015af59f2536e366b5134511a2a70
